baseURL = "https://Q040512.github.io"
title = "Q"
theme = "hugo-theme-bootstrap" # install via git submodule
# theme = "github.com/razonyang/hugo-theme-bootstrap" # install via hugo module
copyright = "Copyright © 2024-{year} Q. All Rights Reserved."

publishDir = "docs"
cleanDestinationDir = true

# Multilingual mode
defaultContentLanguage = "zh-hans"
defaultContentLanguageInSubdir = true # If you use only one language comment this option
# disableLanguages = ["fr", "zh-cn" ,"zh-tw", "ar", "ja"] # Uncomment in order to disable one or more language

# Pagination
[pagination]
pagerSize = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

enableRobotsTXT = true

enableEmoji = true

enableGitInfo = true

# hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

timeout = "120s"

[services]
  # Google analytics
  # [services.googleAnalytics]
  #   ID = 'G-MEASUREMENT_ID'

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[build]
  writeStats = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'PWD']
