[[main]]
  identifier = "home"
  name = "主页"
  weight = 1
  url = "https://hbs.razonyang.com/"
  [main.params]
    icon = '<i class="fas fa-home"></i>'
[[main]]
  identifier = "blog"
  name = "博客"
  weight = 2
  [main.params]
    icon = '<i class="fas fa-fw fa-blog"></i>'
